---
- name: Setup Environment
  hosts: localhost
  gather_facts: no
  roles:
    - provision

- name: Deploy Undercloud
  hosts: localhost
  gather_facts: no
  roles:
    - undercloud

- name:  Deploy Overcloud
  hosts: virthost
  gather_facts: no
  roles:
    - overcloud
