---
- name: Provision hosts 0
  hosts: host0
  vars:
    - ansible_ssh_user: root
  gather_facts: no
  tasks:
    - name: provision hosts
      os_tripleo_provision:
        repo: ['http://trunk.rdoproject.org/centos7/delorean-deps.repo']

# http://docs.ansible.com/ansible/developing_api.html#detailed-api-example
